# Generated by Django 3.0.7 on 2023-09-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, db_index=True)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('trashed', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('system_message', models.TextField()),
                ('user_message', models.TextField()),
                ('output', models.TextField()),
                ('bookmarked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('maximum_length', models.PositiveIntegerField(default=256)),
                ('stop_sequence', models.CharField(default='0', max_length=255)),
                ('top_p', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('frequency_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('presence_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('logit_bias', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('history_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_prompts', to='prompt.Prompt')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='workspace.Workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
