version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "yamak.nginx"
    ports:
      - 80:80
    depends_on:
      - webserver

  webserver:
    image: yamak
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yamak.webserver
    ports: 
      - 8001:8001      
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
      - ./env
      - ./mysql.env
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: "yamak.mysql"
    environment:
      - MYSQL_DATABASE=yamak
      - MYSQL_USER=yamak_local
      - MYSQL_ROOT_PASSWORD=Passwor@123
      - MYSQL_PASSWORD=Passwor@123
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/db:/var/lib/mysql