import decouple
SECRET_KEY=decouple.config("SECRET_KEY")
DEBUG=decouple.config("DEBUG",cast=bool)
JWT_TOKEN_LIFE=decouple.config("JWT_TOKEN_LIFE",cast=int)
JWT_SLIDING_REFRESH_LIFETIME=decouple.config("JWT_SLIDING_REFRESH_LIFETIME",cast=int)
JWT_SLIDING_LIFETIME=decouple.config("JWT_SLIDING_LIFETIME",cast=int)
JWT_GRACE=decouple.config("JWT_GRACE",cast=int)
EMAIL=decouple.config("EMAIL")
EMAIL_PASSWORD=decouple.config("EMAIL_PASSWORD")
MYSQL_DATABASE=decouple.config("DB_NAME")
MYSQL_USER=decouple.config("DB_HOST")
MYSQL_ROOT_PASSWORD=decouple.config("DB_PASSWORD")
MYSQL_PASSWORD=decouple.config("DB_PASSWORD")
MYSQL_PORT=decouple.config("DB_PORT", cast=int)
MYSQL_HOST=decouple.config("DB_HOST")