# Generated by Django 3.0.7 on 2023-09-19 18:59

import uuid

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('OpenAI', 'OPENAI'), ('Bard', 'BARD')], default='OpenAI', max_length=64)),
                ('description', models.TextField(default='')),
                ('api_key', fernet_fields.fields.EncryptedTextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
