# Generated by Django 3.0.7 on 2023-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0002_auto_20230923_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymanagement',
            name='provider',
            field=models.CharField(choices=[('OpenAI', 'OPENAI'), ('Bard', 'BARD')], max_length=64),
        ),
    ]
